# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app_bundle.doctrine.orm.collection_date_filter:
        class:      AppBundle\Doctrine\Orm\Filter\CollectionDateFilter
        arguments:  [ @doctrine ]
        public:     false

# Examples of API resource mapping, learn more at
# https://github.com/dunglas/DunglasApiBundle

    resource.event.order_filter:
        parent:    "api.doctrine.orm.order_filter"
        arguments: [ { "startDate": ~, "endDate": ~ } ]

    resource.event.search_filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { name: "partial", description: "partial" } ]

    resource.event.occurrences_date_filter:
        parent:    "app_bundle.doctrine.orm.collection_date_filter"
        arguments: [ occurrences, { startDate: ~, endDate: ~ } ]

    resource.event:
        parent:      "api.resource"
        arguments: [ "AppBundle\\Entity\\Event" ]
        calls:
            - method:    "initFilters"
              arguments: [ [ "@resource.event.order_filter", "@resource.event.search_filter", "@resource.event.occurrences_date_filter" ] ]
            - method:    "initNormalizationContext"
              arguments: [ { groups: [ "event_read" ] } ]
            - method:    "initDenormalizationContext"
              arguments: [ { groups: [ "event_write" ] } ]
        tags:      [ { name: "api.resource" } ]

    resource.occurrence:
        parent:      "api.resource"
        arguments: [ "AppBundle\\Entity\\Occurrence" ]
        tags:      [ { name: "api.resource" } ]

    # https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048
    fos_user.doctrine_registry:
        alias: doctrine

    security.access.event_voter:
        class:      AppBundle\Security\Authorization\Voter\EventVoter
        public:     false
        tags:
            - { name: security.voter }

    # https://api-platform.com/doc/1.0/api-bundle/the-event-system
    event.event_listener:
        class: AppBundle\EventListener\EventListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: api.pre_update, method: onPreUpdate }
            - { name: kernel.event_listener, event: api.pre_delete, method: onPreDelete }

    feed_reader.json:
        class: AdminBundle\Service\FeedReader\Json

    feed_reader.xml:
        class: AdminBundle\Service\FeedReader\Xml
